SELECT
JOB_TITLE AS 'Cargo',
CAST(AVG(SALARY) AS DECIMAL(10,2)) AS 'Média salarial',
(CASE 
  WHEN AVG(SALARY) >= 2000 AND AVG(SALARY) <= 5800 THEN 'Júnior'
  WHEN AVG(SALARY) >= 5801 AND AVG(SALARY) <= 7500 THEN 'Pleno'
  WHEN AVG(SALARY) >= 7501 AND AVG(SALARY) <= 10500 THEN 'Sênior'
  WHEN AVG(SALARY) > 10500 THEN 'CEO'
  ELSE ''
END)
AS 'Senioridade'
FROM hr.jobs
LEFT JOIN hr.employees AS a
ON hr.jobs.JOB_ID = a.JOB_ID
GROUP BY hr.jobs.JOB_ID
ORDER BY AVG(SALARY), Cargo;
