SELECT
JOB_TITLE AS 'Cargo',
(MAX_SALARY - MIN_SALARY) AS 'Média salarial',
(CASE 
  WHEN (MAX_SALARY - MIN_SALARY) >= 2000 AND (MAX_SALARY - MIN_SALARY) <= 5800 THEN 'Júnior'
  WHEN (MAX_SALARY - MIN_SALARY) >= 5801 AND (MAX_SALARY - MIN_SALARY) <= 7500 THEN 'Pleno'
  WHEN (MAX_SALARY - MIN_SALARY) >= 7501 AND (MAX_SALARY - MIN_SALARY) <= 10500 THEN 'Sênior'
  WHEN (MAX_SALARY - MIN_SALARY) > 10500 THEN 'CEO'
  ELSE ''
END)
AS 'Senioridade'
FROM hr.jobs
ORDER BY (MAX_SALARY - MIN_SALARY), Cargo;